#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Quick Start Guide - YOLO Pose Conducting

This script demonstrates the simplest way to use YOLO pose tracking
for conducting gestures.
"""

def print_guide():
    """Print quick start guide."""
    print("=" * 70)
    print("YOLO POSE CONDUCTING - QUICK START GUIDE")
    print("=" * 70)
    print()
    print("BASIC USAGE:")
    print("-" * 70)
    print("  python demo_finger_conducting.py --use_yolo")
    print()
    print("FEATURES:")
    print("-" * 70)
    print("  ✓ Tracks your wrist position (right or left)")
    print("  ✓ Natural conducting gestures with your arm")
    print("  ✓ Beat detection at lowest point of downward motion")
    print("  ✓ Automatic tempo calibration with countdown")
    print()
    print("ADVANTAGES OVER HAND TRACKING:")
    print("-" * 70)
    print("  • Works from further away (full body visible)")
    print("  • More natural conducting movements")
    print("  • Faster inference on GPU")
    print("  • Robust to hand occlusions")
    print()
    print("REQUIREMENTS:")
    print("-" * 70)
    print("  1. Install ultralytics:  pip install ultralytics")
    print("  2. Have yolo11s-pose.pt in project root (auto-downloads)")
    print("  3. Position yourself so upper body is visible")
    print()
    print("CONTROLS:")
    print("-" * 70)
    print("  SPACE - Start countdown calibration / Pause")
    print("  H     - Switch wrist (left/right)")
    print("  2/3/4 - Change time signature")
    print("  R     - Reset conducting state")
    print("  ESC   - Exit")
    print()
    print("EXAMPLES:")
    print("-" * 70)
    print("  # Use with right wrist (default)")
    print("  python demo_finger_conducting.py --use_yolo")
    print()
    print("  # Use with left wrist")
    print("  python demo_finger_conducting.py --use_yolo --primary_hand left")
    print()
    print("  # Use faster model for better FPS")
    print("  python demo_finger_conducting.py --use_yolo --yolo_model yolo11n-pose.pt")
    print()
    print("  # Use more accurate model")
    print("  python demo_finger_conducting.py --use_yolo --yolo_model yolo11m-pose.pt")
    print()
    print("  # With custom MIDI file")
    print("  python demo_finger_conducting.py --use_yolo --song_path mysong.mid")
    print()
    print("TIPS:")
    print("-" * 70)
    print("  • Stand 1-2 meters from camera for best results")
    print("  • Ensure your upper body and arms are fully visible")
    print("  • Use large, clear conducting motions")
    print("  • Start with 4/4 time signature (easiest)")
    print("  • The beat occurs at the BOTTOM of your downward motion")
    print()
    print("TROUBLESHOOTING:")
    print("-" * 70)
    print("  No wrist detected:")
    print("    → Move closer to camera")
    print("    → Ensure arms are not behind your body")
    print("    → Improve lighting")
    print()
    print("  Low FPS:")
    print("    → Use yolo11n-pose.pt (nano model)")
    print("    → Reduce camera resolution: --width 640 --height 480")
    print("    → Enable GPU if available")
    print()
    print("  Beat detection not working:")
    print("    → Make larger, clearer downward motions")
    print("    → Conduct with more vertical movement")
    print("    → Press 'R' to reset if analyzer gets stuck")
    print()
    print("COMPARISON:")
    print("-" * 70)
    print("  MediaPipe (default)      | YOLO Pose (--use_yolo)")
    print("  ------------------------ | -------------------------")
    print("  Finger tracking          | Wrist tracking")
    print("  Close range              | Medium-far range")
    print("  Dual-hand volume control | Single-point conducting")
    print("  Gesture recognition      | Position only")
    print("  21 hand landmarks        | 17 body keypoints")
    print()
    print("For detailed documentation, see: YOLO_TRACKING.md")
    print("=" * 70)


if __name__ == '__main__':
    print_guide()
